spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service:8082
          predicates:
           - Path=employees/**
        - id: department-service
          uri: lb://department-service:8081
          predicates:
            - Path=departments/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8060
